services:
    tools_bundle.webhookmanager:
        class: VisageFour\Bundle\ToolsBundle\Services\WebHookManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@buzz"
            - "@logger"


    tools_bundle.code_manager:
        class: VisageFour\Bundle\ToolsBundle\Services\CodeManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "VisageFour\Bundle\PersonBundle\Entity\Code"
            - "@event_dispatcher"
            - "@logger"

    visage_four.base_person_manager:
        class: VisageFour\Bundle\PersonBundle\Services\BasePersonManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "VisageFour\Bundle\PersonBundle\Entity\BasePerson"
            - "@event_dispatcher"
            - "@logger"