services:
    _defaults:
        autowire: true
        autoconfigure: true

#    VisageFour\Bundle\ToolsBundle\:
#        resource: '../../src/VisageFour/Bundle/ToolsBundle/*'
#        exclude: '../../src/VisageFour/Bundle/ToolsBundle/{Entity,Exceptions,Classes/noAutowire}'

    tools_bundle.webhookmanager:
        class: VisageFour\Bundle\ToolsBundle\Services\WebHookManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@buzz"
            - "@logger"
            - "%env(DISABLE_WEBHOOK_CALLS)%"

    tools_bundle.code_manager:
        class: VisageFour\Bundle\ToolsBundle\Services\CodeManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - 'VisageFour\Bundle\ToolsBundle\Entity\Code'
            - "@event_dispatcher"
            - "@logger"

    tools_bundle.code_slug_converter:
        class: VisageFour\Bundle\ToolsBundle\Request\ParamConverter\CodeSlugParamConverter
        tags:
            - { name: request.param_converter, converter: code_slug_converter }
        arguments:
            - "@?doctrine"
            - "@doctrine.orm.entity_manager"
#
#    VisageFour\Bundle\ToolsBundle\Form\BaseFormType:
#        arguments:
#            $kernelEnv: "%kernel.environment%"

# add this to your projects services.yml, not in the shared VisageFour services.yml as it will crash the app if lexik mailer is not installed.
#    anchorcards.email_register_manager:
#        class: VisageFour\Bundle\ToolsBundle\Services\EmailRegisterManager
#        arguments:
#            - "@doctrine.orm.entity_manager"
#            - "ToolsBundle:EmailRegister"
#            - "@event_dispatcher"
#            - "@logger"
#            - "@lexik_mailer.message_factory"
#            - "@mailer"