services:
    tools_bundle.webhookmanager:
        class: VisageFour\Bundle\ToolsBundle\Services\WebHookManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@buzz"
            - "@logger"


    tools_bundle.code_manager:
        class: VisageFour\Bundle\ToolsBundle\Services\CodeManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - 'VisageFour\Bundle\ToolsBundle\Entity\Code'
            - "@event_dispatcher"
            - "@logger"