services:
    toolsbundle.webhookmanager:
        class: VisageFour\Bundle\ToolsBundle\Services\WebHookManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@buzz"
            - "@logger"