<?php

namespace VisageFour\Bundle\ToolsBundle\Repository;

/**
 * CarrierNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarrierNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
