<?php

namespace VisageFour\Bundle\ToolsBundle\Repository;
use Doctrine\ORM\EntityManager;
use Platypuspie\AnchorcardsBundle\Entity\Codes;
use Platypuspie\AnchorcardsBundle\Entity\shoot;
use VisageFour\Bundle\ToolsBundle\Entity\Code;

/**
 * codeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeRepository extends \Doctrine\ORM\EntityRepository
{
}
