<?php

namespace VisageFour\Bundle\ToolsBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use VisageFour\Bundle\ToolsBundle\Entity\EmailRegister;

/**
 * EmailRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRegisterRepository  extends ServiceEntityRepository
{
    public function countSpooled () {
        $qb = $this->createQueryBuilder('er')
            ->select('COUNT(er)')
            ->where('er.sendStatus = :status')
            ->setParameter('status',     EmailRegister::SPOOLED)
        ;

        return  $qb->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
