<?php

namespace VisageFour\Bundle\ToolsBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * SlugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlugRepository extends ServiceEntityRepository
{
    public function __construct (ManagerRegistry $registry) {
        parent::__construct($registry, SlugRepository::class);
    }
}
