<?php

namespace VisageFour\Bundle\ToolsBundle\Statics;

/**
 * Created by PhpStorm.
 * User: CamBurns
 * Date: 12/10/2016
 * Time: 4:34 PM
 */

// folder: Statics contains static arrays that projects may want to use in different ways
class StaticInternational
{
    public static $residencyOptions = array (
        'workVisa'      => 'Working Holiday',
        'studentVisa'   => 'Student Visa',
        'PR'            => 'Permanent Resident (PR)',
        'ausCitizen'    => 'Australian Citizen'
    );

    // countries
    public static $countries = array(
        'AF' => 'Afghanistan',
        'AX' => 'Aland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua And Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia And Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, Democratic Republic',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Cote D\'Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island & Mcdonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic Of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle Of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KR' => 'Korea',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libyan Arab Jamahiriya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States Of',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory, Occupied',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthelemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts And Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin',
        'PM' => 'Saint Pierre And Miquelon',
        'VC' => 'Saint Vincent And Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome And Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia And Sandwich Isl.',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard And Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad And Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks And Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis And Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe'
    );

    // languages - remember to use sort() to get inalphabetical order (if required)
    public static $languages = array (
        'Empty' => 'Empty',
        'aa' => 'Afar',
        'ab' => 'Abkhaz',
        'ae' => 'Avestan',
        'af' => 'Afrikaans',
        'ak' => 'Akan',
        'am' => 'Amharic',
        'an' => 'Aragonese',
        'ar' => 'Arabic',
        'as' => 'Assamese',
        'av' => 'Avaric',
        'ay' => 'Aymara',
        'az' => 'Azerbaijani',
        'ba' => 'Bashkir',
        'be' => 'Belarusian',
        'bg' => 'Bulgarian',
        'bh' => 'Bihari',
        'bi' => 'Bislama',
        'bm' => 'Bambara',
        'bn' => 'Bengali',
        'bo' => 'Tibetan Standard, Tibetan, Central',
        'bp' => 'Brazillian Portuguese',
        'br' => 'Breton',
        'bs' => 'Bosnian',
        'ca' => 'Catalan; Valencian',
        'ce' => 'Chechen',
        'ch' => 'Chamorro',
        'co' => 'Corsican',
        'cr' => 'Cree',
        'cs' => 'Czech',
        'cu' => 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
        'cv' => 'Chuvash',
        'cy' => 'Welsh',
        'cz' => 'Chinese',
        'da' => 'Danish',
        'de' => 'German',
        'dv' => 'Divehi; Dhivehi; Maldivian;',
        'dz' => 'Dzongkha',
        'ee' => 'Ewe',
        'el' => 'Greek, Modern',
        'en' => 'English',
        'eo' => 'Esperanto',
        'es' => 'Spanish; Castilian',       // todo: needs to be updated to 'Spanish' only
        'et' => 'Estonian',
        'eu' => 'Basque',
        'fa' => 'Persian',
        'ff' => 'Fula; Fulah; Pulaar; Pular',
        'fi' => 'Finnish',
        'fj' => 'Fijian',
        'fl' => 'Filipino',
        'fo' => 'Faroese',
        'fr' => 'French',
        'fy' => 'Western Frisian',
        'ga' => 'Irish',
        'gd' => 'Scottish Gaelic; Gaelic',
        'gl' => 'Galician',
        'gn' => 'GuaranÃ­',
        'gu' => 'Gujarati',
        'gv' => 'Manx',
        'ha' => 'Hausa',
        'he' => 'Hebrew (modern)',
        'hi' => 'Hindi',
        'ho' => 'Hiri Motu',
        'hr' => 'Croatian',
        'ht' => 'Haitian; Haitian Creole',
        'hu' => 'Hungarian',
        'hy' => 'Armenian',
        'hz' => 'Herero',
        'ia' => 'Interlingua',
        'id' => 'Indonesian',
        'ie' => 'Interlingue',
        'ig' => 'Igbo',
        'ii' => 'Nuosu',
        'ik' => 'Inupiaq',
        'io' => 'Ido',
        'is' => 'Icelandic',
        'it' => 'Italian',
        'iu' => 'Inuktitut',
        'ja' => 'Japanese (ja)',
        'jc' => 'Javanese (jv)',
        'ka' => 'Georgian',
        'kg' => 'Kongo',
        'ki' => 'Kikuyu, Gikuyu',
        'kj' => 'Kwanyama, Kuanyama',
        'kk' => 'Kazakh',
        'kl' => 'Kalaallisut, Greenlandic',
        'km' => 'Khmer',
        'kn' => 'Kannada',
        'ko' => 'Korean',
        'kr' => 'Kanuri',
        'ks' => 'Kashmiri',
        'ku' => 'Kurdish',
        'kv' => 'Komi',
        'kw' => 'Cornish',
        'ky' => 'Kirghiz, Kyrgyz',
        'la' => 'Latin',
        'lb' => 'Luxembourgish, Letzeburgesch',
        'lg' => 'Luganda',
        'li' => 'Limburgish, Limburgan, Limburger',
        'ln' => 'Lingala',
        'lo' => 'Lao',
        'lt' => 'Lithuanian',
        'lu' => 'Luba-Katanga',
        'lv' => 'Latvian',
        'mg' => 'Malagasy',
        'mh' => 'Marshallese',
        'mi' => 'Maori',
        'mk' => 'Macedonian',
        'ml' => 'Malayalam',
        'mn' => 'Mongolian',
        'mr' => 'Marathi (Mara?hi)',
        'ms' => 'Malay',
        'mt' => 'Maltese',
        'my' => 'Burmese',
        'na' => 'Nauru',
        'nb' => 'Norwegian BokmÃ¥l',
        'nd' => 'North Ndebele',
        'ne' => 'Nepali',
        'ng' => 'Ndonga',
        'nl' => 'Dutch',
        'nn' => 'Norwegian Nynorsk',
        'no' => 'Norwegian',
        'nr' => 'South Ndebele',
        'nv' => 'Navajo, Navaho',
        'ny' => 'Chichewa; Chewa; Nyanja',
        'oc' => 'Occitan',
        'oj' => 'Ojibwe, Ojibwa',
        'om' => 'Oromo',
        'or' => 'Oriya',
        'os' => 'Ossetian, Ossetic',
        'pa' => 'Panjabi, Punjabi',
        'pi' => 'Pali',
        'pl' => 'Polish',
        'ps' => 'Pashto, Pushto',
        'pt' => 'Jamaican Patois',
        'pr' => 'Portuguese',
        'qu' => 'Quechua',
        'rm' => 'Romansh',
        'rn' => 'Kirundi',
        'ro' => 'Romanian, Moldavian, Moldovan',
        'ru' => 'Russian',
        'rw' => 'Kinyarwanda',
        'sa' => 'Sanskrit (Sa?sk?ta)',
        'sc' => 'Sardinian',
        'sd' => 'Sindhi',
        'se' => 'Northern Sami',
        'sg' => 'Sango',
        'si' => 'Sinhala, Sinhalese',
        'sk' => 'Slovak',
        'sl' => 'Slovene',
        'sm' => 'Samoan',
        'sn' => 'Shona',
        'so' => 'Somali',
        'sq' => 'Albanian',
        'sr' => 'Serbian',
        'ss' => 'Swati',
        'st' => 'Southern Sotho',
        'su' => 'Sundanese',
        'sv' => 'Swedish',
        'sw' => 'Swahili',
        'ta' => 'Tamil',
        'te' => 'Telugu',
        'tg' => 'Tajik',
        'th' => 'Thai',
        'ti' => 'Tigrinya',
        'tk' => 'Turkmen',
        'tl' => 'Tagalog',
        'tn' => 'Tswana',
        'to' => 'Tonga (Tonga Islands)',
        'tr' => 'Turkish',
        'ts' => 'Tsonga',
        'tt' => 'Tatar',
        'tw' => 'Twi',
        'ty' => 'Tahitian',
        'ug' => 'Uighur, Uyghur',
        'uk' => 'Ukrainian',
        'ur' => 'Urdu',
        'uz' => 'Uzbek',
        've' => 'Venda',
        'vi' => 'Vietnamese',
        'vo' => 'VolapÃ¼k',
        'wa' => 'Walloon',
        'wo' => 'Wolof',
        'xh' => 'Xhosa',
        'yi' => 'Yiddish',
        'yo' => 'Yoruba',
        'za' => 'Zhuang, Chuang',
        'zu' => 'Zulu'
    );

    // a list of country keys that map to their default native language (uses array keys from other statics on this page.)
    public static $defaultNativeLanguage = array (
        'AF' => 'ps',           // Afghanistan -> Pashto and dari
        'AX' => null,           // Aland Islands -> ?
        'AL' => 'sq',           // Albania -> Albanian
        'DZ' => 'ar',           // Algeria -> arabic
        'AS' => null,           // American Samoa -> ?
        'AD' => null,           // Andorra -> ?
        'AO' => null,           // Angola -> ?
        'AI' => null,           // Anguilla -> ?
        'AQ' => null,           // Antarctica ->
        'AG' => null,           // Antigua And Barbuda
        'AR' => 'es',           // Argentina -> spanish
        'AM' => 'hy',           // Armenia -> Armenian
        'AW' => null,           // Aruba ->
        'AU' => 'en',           // Australia -> English
        'AT' => 'de',           // Austria -> German and Slovenian
        'AZ' => null,           // Azerbaijan
        'BS' => null,           // Bahamas
        'BH' => null,           // Bahrain
        'BD' => 'bn',           // Bangladesh -> Bengali
        'BB' => null,           // arbados
        'BY' => null,           // Belarus
        'BE' => 'fr',           // Belgium -> French, Germna, Dutch
        'BZ' => null,           // Belize
        'BJ' => null,           // Benin
        'BM' => null,           // Bermuda
        'BT' => null,           // Bhutan
        'BO' => 'es',           // Bolivia
        'BA' => null,           // Bosnia And Herzegovina
        'BW' => null,           // Botswana
        'BV' => null,           // Bouvet Island
        'BR' => 'bp',           // Brazil -> Brazillian Portuguese
        'IO' => null,           // British Indian Ocean Territory
        'BN' => null,           // Brunei Darussalam
        'BG' => null,           // Bulgaria
        'BF' => null,           // Burkina Faso
        'BI' => null,           // Burundi
        'KH' => 'km',           // Cambodia -> Khmer
        'CM' => null,           // Cameroon
        'CA' => 'en',           // Canada -> English, French
        'CV' => null,           // Cape Verde
        'KY' => null,           // Cayman Islands
        'CF' => null,           // Central African Republic
        'TD' => null,           // Chad
        'CL' => 'es',           // Chile -> spanish
        'CN' => 'cz',           // China -> Mandarin
        'CX' => null,           // Christmas Island
        'CC' => null,           // Cocos (Keeling) Islands
        'CO' => null,           // Colombia
        'KM' => null,           // Comoros
        'CG' => null,           // Congo
        'CD' => null,           // Congo, Democratic Republic
        'CK' => null,           // Cook Islands
        'CR' => 'es',           // Costa Rica -> Spanish
        'CI' => null,           // Cote D\'Ivoire
        'HR' => 'hr',           // Croatia -> Croatian
        'CU' => 'es',           // Cuba -> Spanish
        'CY' => null,           // Cyprus
        'CZ' => null,           // Czech Republic
        'DK' => null,           // Denmark
        'DJ' => null,           // Djibouti
        'DM' => null,           // Dominica
        'DO' => null,           // Dominican Republic
        'EC' => 'es',           // Ecuador -> Spanish
        'EG' => 'ar',           // Egypt -> Arabic
        'SV' => null,           // El Salvador
        'GQ' => null,           // Equatorial Guinea
        'ER' => null,           // Eritrea
        'EE' => null,           // Estonia
        'ET' => null,           // Ethiopia
        'FK' => null,           // Falkland Islands (Malvinas)
        'FO' => null,           // Faroe Islands
        'FJ' => 'fj',           // Fiji -> Fijian
        'FI' => 'fi',           // Finland -> Finnish, Swedish
        'FR' => 'fr',           // France -> French
        'GF' => null,           // French Guiana
        'PF' => null,           // French Polynesia
        'TF' => null,           // French Southern Territories
        'GA' => null,           // Gabon
        'GM' => null,           // Gambia
        'GE' => null,           // Georgia
        'DE' => 'de',           // Germany -> German
        'GH' => null,           // Ghana
        'GI' => null,           // Gibraltar
        'GR' => 'el',           // Greece -> Greek
        'GL' => null,           // Greenland
        'GD' => null,           // Grenada
        'GP' => null,           // Guadeloupe
        'GU' => null,           // Guam
        'GT' => 'es',           // Guatemala -> Spanish
        'GG' => null,           // Guernsey
        'GN' => null,           // Guinea
        'GW' => null,           // Guinea-Bissau
        'GY' => null,           // Guyana
        'HT' => null,           // Haiti
        'HM' => null,           // Heard Island & Mcdonald Islands
        'VA' => null,           // Holy See (Vatican City State)
        'HN' => null,           // Honduras
        'HK' => 'cz',           // Hong Kong -> Mandarin, English
        'HU' => null,           // Hungary
        'IS' => 'is',           // Iceland -> Icelandic
        'IN' => 'hi',           // India -> Hindi
        'ID' => 'id',           // Indonesia -> Indonesian
        'IR' => 'fa',           // Iran, Islamic Republic Of -> Persian
        'IQ' => 'ar',           // Iraq -> Arabic
        'IE' => 'ga',           // Ireland -> Irish
        'IM' => null,           // Isle Of Man
        'IL' => 'he',           // Israel -> Hebrew
        'IT' => 'it',           // Italy -> Italian
        'JM' => 'ps',           // Jamaica -> Jamaican Patois
        'JP' => 'ja',           // Japan -> Japanese
        'JE' => null,           // Jersey
        'JO' => null,           // Jordan
        'KZ' => null,           // Kazakhstan
        'KE' => 'sw',           // Kenya -> Swahili
        'KI' => null,           // Kiribati
        'KR' => 'ko',           // Korea -> Korean
        'KW' => null,           // Kuwait
        'KG' => null,           // Kyrgyzstan
        'LA' => null,           // Lao People\'s Democratic Republic
        'LV' => null,           // Latvia
        'LB' => 'ar',           // Lebanon -> Arabic
        'LS' => null,           // Lesotho
        'LR' => null,           // Liberia
        'LY' => null,           // Libyan Arab Jamahiriya
        'LI' => null,           // Liechtenstein
        'LT' => 'lt',           // Lithuania -> Lithuanian
        'LU' => null,           // Luxembourg
        'MO' => null,           // Macao
        'MK' => null,           // Macedonia
        'MG' => null,           // Madagascar
        'MW' => null,           // Malawi
        'MY' => 'ms',           // Malaysia -> Malay
        'MV' => null,           // Maldives
        'ML' => null,           // Mali
        'MT' => null,           // Malta
        'MH' => null,           // Marshall Islands
        'MQ' => null,           // Martinique
        'MR' => null,           // Mauritania
        'MU' => 'en',           // Mauritius -> English
        'YT' => null,           // Mayotte
        'MX' => 'es',           // Mexico -> Spanish
        'FM' => null,           // Micronesia, Federated States Of
        'MD' => null,           // Moldova
        'MC' => null,           // Monaco
        'MN' => 'mn',           // Mongolia -> Mongolian
        'ME' => null,           // Montenegro
        'MS' => null,           // Montserrat
        'MA' => null,           // Morocco
        'MZ' => null,           // Mozambique
        'MM' => null,           // Myanmar
        'NA' => null,           // Namibia
        'NR' => null,           // Nauru
        'NP' => 'ne',           // Nepal -> Nepali
        'NL' => 'nl',           // Netherlands -> Dutch
        'AN' => null,           // Netherlands Antilles
        'NC' => 'fr',           // New Caledonia -> French
        'NZ' => 'en',           // New Zealand -> English
        'NI' => null,           // Nicaragua
        'NE' => null,           // Niger
        'NG' => null,           // Nigeria
        'NU' => null,           // Niue
        'NF' => null,           // Norfolk Island
        'MP' => null,           // Northern Mariana Islands
        'NO' => null,           // Norway
        'OM' => 'ar',           // Oman -> Arabic
        'PK' => 'ur',           // Pakistan -> Urdu
        'PW' => null,           // Palau
        'PS' => 'ar',           // Palestinian Territory, Occupied -> Arabic
        'PA' => null,           // Panama
        'PG' => 'en',           // Papua New Guinea -> English
        'PY' => 'es',           // Paraguay -> Spanish
        'PE' => 'es',           // Peru -> Spanish
        'PH' => 'fl',           // Philippines -> Filipino
        'PN' => null,           // Pitcairn
        'PL' => 'pl',           // Poland -> Polish
        'PT' => 'pr',           // Portugal -> Portuguese
        'PR' => 'es',           // Puerto Rico -> Spanish
        'QA' => 'ar',           // Qatar -> Arabic
        'RE' => null,           // Reunion
        'RO' => 'ro',           // Romania -> Romanian
        'RU' => 'ru',           // Russian Federation -> Russian
        'RW' => null,           // Rwanda
        'BL' => null,           // Saint Barthelemy
        'SH' => null,           // Saint Helena
        'KN' => null,           // Saint Kitts And Nevis
        'LC' => null,           // Saint Lucia
        'MF' => null,           // Saint Martin
        'PM' => null,           // Saint Pierre And Miquelon
        'VC' => null,           // Saint Vincent And Grenadines
        'WS' => null,           // Samoa
        'SM' => null,           // San Marino
        'ST' => null,           // Sao Tome And Principe
        'SA' => null,           // Saudi Arabia
        'SN' => null,           // Senegal
        'RS' => null,           // Serbia
        'SC' => null,           // Seychelles
        'SL' => null,           // Sierra Leone
        'SG' => 'en',           // Singapore -> English
        'SK' => null,           // Slovakia
        'SI' => null,           // Slovenia
        'SB' => null,           // Solomon Islands
        'SO' => null,           // Somalia
        'ZA' => null,           // South Africa
        'GS' => null,           // South Georgia And Sandwich Isl.
        'ES' => 'es',           // Spain -> Spanish
        'LK' => 'si',           // Sri Lanka -> Sinhala, English, Tamil
        'SD' => 'ar',           // Sudan -> Arabic
        'SR' => null,           // Suriname
        'SJ' => null,           // Svalbard And Jan Mayen
        'SZ' => null,           // Swaziland
        'SE' => 'sv',           // Sweden -> Swedish
        'CH' => 'fr',           // Switzerland -> French, Italian, German, Romansh
        'SY' => 'ar',           // Syrian Arab Republic -> Arabic
        'TW' => 'cz',           // Taiwan -> Mandarin
        'TJ' => 'tg',           // Tajikistan -> Tajik
        'TZ' => 'sw',           // Tanzania -> Swahili
        'TH' => 'th',           // Thailand -> Thai
        'TL' => null,           // Timor-Leste
        'TG' => null,           // Togo
        'TK' => null,           // Tokelau
        'TO' => null,           // Tonga
        'TT' => null,           // Trinidad And Tobago
        'TN' => 'ar',           // Tunisia -> Arabic
        'TR' => 'tr',           // Turkey -> Turkish
        'TM' => null,           // Turkmenistan
        'TC' => null,           // Turks And Caicos Islands
        'TV' => 'en',           // Tuvalu -> English
        'UG' => 'en',           // Uganda -> English, Swahili
        'UA' => 'uk',           // Ukraine -> Ukrainian
        'AE' => 'ar',           // United Arab Emirates -> Arabic
        'GB' => 'en',           // United Kingdom -> English
        'US' => 'en',           // United States -> English
        'UM' => null,           // United States Outlying Islands
        'UY' => 'es',           // Uruguay -> Spanish
        'UZ' => null,           // Uzbekistan
        'VU' => 'fr',           // Vanuatu -> French
        'VE' => 'es',           // Venezuela -> Spanish
        'VN' => 'vi',           // Viet Nam -> Vietnamese
        'VG' => null,           // Virgin Islands, British
        'VI' => null,           // Virgin Islands, U.S.
        'WF' => null,           // Wallis And Futuna
        'EH' => null,           // Western Sahara
        'YE' => 'ar',           // Yemen -> Arabic
        'ZM' => 'en',           // Zambia -> English
        'ZW' => 'en',           // Zimbabwe -> English
    );
    // todo: Australian states

    // todo: Victorian suburbs

}